<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" ignored="2" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="ECommerceProject" duration-ms="99088" started-at="2018-03-12T10:38:08Z" finished-at="2018-03-12T10:39:47Z">
    <groups>
    </groups>
    <test name="Unit Test cases " duration-ms="99088" started-at="2018-03-12T10:38:08Z" finished-at="2018-03-12T10:39:47Z">
      <class name="com.progrocers.TestCase.FunctionalTestCase">
        <test-method status="PASS" signature="brokenLinks()[pri:0, instance:com.progrocers.TestCase.FunctionalTestCase@47d9a273]" name="brokenLinks" duration-ms="55988" started-at="2018-03-12T10:38:08Z" finished-at="2018-03-12T10:39:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- brokenLinks -->
        <test-method status="PASS" signature="searchAlgorithm()[pri:1, instance:com.progrocers.TestCase.FunctionalTestCase@47d9a273]" name="searchAlgorithm" duration-ms="42746" started-at="2018-03-12T10:39:04Z" finished-at="2018-03-12T10:39:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchAlgorithm -->
        <test-method status="SKIP" signature="createCustomer(java.util.Hashtable)[pri:2, instance:com.progrocers.TestCase.FunctionalTestCase@47d9a273]" name="createCustomer" duration-ms="0" started-at="2018-03-12T10:39:47Z" data-provider="DP" finished-at="2018-03-12T10:39:47Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NegativeArraySizeException]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NegativeArraySizeException
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:923)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NegativeArraySizeException
at com.progrocers.Utilities.TestUtil.getdata(TestUtil.java:82)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 25 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createCustomer -->
      </class> <!-- com.progrocers.TestCase.FunctionalTestCase -->
      <class name="com.progrocers.Base.TestBase">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.progrocers.Base.TestBase@26e356f0]" name="setUp" is-config="true" duration-ms="30496" started-at="2018-03-12T10:37:37Z" finished-at="2018-03-12T10:38:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="finish()[pri:0, instance:com.progrocers.Base.TestBase@26e356f0]" name="finish" is-config="true" duration-ms="613" started-at="2018-03-12T10:39:47Z" finished-at="2018-03-12T10:39:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finish -->
      </class> <!-- com.progrocers.Base.TestBase -->
    </test> <!-- Unit Test cases  -->
  </suite> <!-- ECommerceProject -->
</testng-results>
